[server]
  addr = "127.0.0.1"
  port = 8080
  env = "debug"
  gracefulShutdownPeriod = 30

[mysql]
  host = "localhost"
  port = 3306
  name =  "baby_daily"
  user = "root"
  pass = "123456"
  maxIdleConn = 5
  maxOpenConn = 20
  connMaxLifeTime = 60
  loggerLevel = "info"

[redis]
  addr = "127.0.0.1:6379"
  db = 1
  maxretries = 3
  minidleconns = 5
  pass = "123456"
  poolsize = 10

[Wechat]
  appid = '123456'
  secret = '123456'